# Generated by Django 3.0.7 on 2020-06-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
