# Generated by Django 3.0.7 on 2020-06-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebuddy', '0002_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_released',
            field=models.CharField(max_length=100),
        ),
    ]
