# Generated by Django 3.0.7 on 2020-06-12 15:40

from django.db import migrations

def seed(apps, schema_editor):
    Movie = apps.get_model('moviebuddy', 'Movie')
    Review = apps.get_model('moviebuddy', 'Review')

    jojo = Movie(title= "Jojo Rabbit",
        description= "Jojo Rabbit is a 2019 American comedy-drama film[3][8] written and directed by Taika Waititi, based on Christine Leunens's 2008 book Caging Skies.[9][10][11] Roman Griffin Davis portrays the title character, Johannes \"Jojo\" Betzler, a Hitler Youth member who finds out his mother (Scarlett Johansson) is hiding a Jewish girl (Thomasin McKenzie) in their attic. He must then question his beliefs, while dealing with the intervention of his imaginary friend, a fanciful version of Adolf Hitler (Waititi) with a comedic stand on the politics of the war. The film also stars Rebel Wilson, Stephen Merchant, Alfie Allen, and Sam Rockwell.",
        image_url= "https://upload.wikimedia.org/wikipedia/en/a/a2/Jojo_Rabbit_%282019%29_poster.jpg",
        trailer_url= "https://youtu.be/tL4McUzXfFI",
        year_released= "2019").save()
    avengers = Movie(title= "Avengers Endgame",
        description= "Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU). It was directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely, and features an ensemble cast including Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Benedict Wong, Jon Favreau, Bradley Cooper, Gwyneth Paltrow, and Josh Brolin. In the film, the surviving members of the Avengers and their allies attempt to reverse the damage caused by Thanos in Infinity War.",
        image_url= "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
        trailer_url= "https://youtu.be/hA6hldpSTF8",
        year_released= "2019").save()
    nineteen = Movie(title= "1917",
        description= "1917 is a 2019 British war film directed, co-written, and produced by Sam Mendes. The film stars George MacKay and Dean-Charles Chapman, with Mark Strong, Andrew Scott, Richard Madden, Claire Duburcq, Colin Firth and Benedict Cumberbatch in supporting roles. It is based in part on an account told to Mendes by his paternal grandfather, Alfred Mendes,[7] and tells the story of two young British soldiers during the First World War who are ordered to deliver a message calling off an attack doomed to fail soon after the German retreat to the Hindenburg Line during Operation Alberich. This message is especially important to one of the soldiers, as his brother is due to take part in the attack.",
        image_url= "https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_SY1000_CR0,0,631,1000_AL_.jpg",
        trailer_url= "https://youtu.be/gZjQROMAh_s",
        year_released= "2019").save()
    little = Movie(title= "Little Women",
        description= "Little Women is a 2019 American coming-of-age period drama film written and directed by Greta Gerwig. It is the seventh film adaptation of the 1868 novel of the same name by Louisa May Alcott. The film stars Saoirse Ronan, Emma Watson, Florence Pugh, Eliza Scanlen, Laura Dern, Timothée Chalamet, Meryl Streep, Tracy Letts, Bob Odenkirk, James Norton, Louis Garrel, and Chris Cooper.",
        image_url= "https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/Little_Women_%282019_film%29.jpeg/220px-Little_Women_%282019_film%29.jpeg",
        trailer_url= "https://youtu.be/AST2-4db4ic",
        year_released= "2019").save()
    knives = Movie(title= "Knives Out",
        description= "Knives Out is a 2019 American mystery film written and directed by Rian Johnson, and produced by Johnson and Ram Bergman. A modern whodunit, the film follows a family gathering gone awry, after the patriarch's death leads a master detective to investigate. The film features an ensemble cast, including Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis, Michael Shannon, Don Johnson, Toni Collette, Lakeith Stanfield, Katherine Langford, Jaeden Martell, and Christopher Plummer.",
        image_url= "https://upload.wikimedia.org/wikipedia/en/1/1f/Knives_Out_poster.jpeg",
        trailer_url= "https://youtu.be/qGqiHJTsRkQ",
        year_released= "2019").save()


    Review(title = 'Lorem ipsum', review_body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', movie = jojo, owner = 1).save()
    Review(title = 'Lorem ipsum', review_body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', movie = avengers, owner = 1).save()
    Review(title = 'Lorem ipsum', review_body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', movie = nineteen, owner = 1).save()
    Review(title = 'Lorem ipsum', review_body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', movie = little, owner = 1).save()
    Review(title = 'Lorem ipsum', review_body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', movie = knives, owner = 1).save()

def fallow(apps, schema_editor):
    Movie = apps.get_model('moviebuddy', 'Movie')
    Movie.objects.all().delete()
    Review = apps.get_model('moviebuddy', 'Review')
    Review.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('moviebuddy', '0003_auto_20200611_2150'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
