# Generated by Django 3.0.7 on 2020-06-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebuddy', '0004_auto_20200612_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(default='https://lh6.googleusercontent.com/proxy/hIgFSMyx4VsuoQh8h-ZfI3IiK9uFSLZ7pG67H_1RwEBDEPiWX-odcJ0PkWriAPeqwKyC6n-12UTrNmQF2ul9DAjwKMljG3zSCCTDoTVDPexFHV9l_JD5WMbmpnUJqWLqYA=s0-d', editable=False),
        ),
    ]
